### ISSUE TITLE
feat: Show image status in the GUI

### ISSUE THREAD

**Issue by jasleon** [artmenlope/LaTeX-to-GitHub-app#1]
The GUI could have an indicator/text to tell the user it failed to show an image. 

It could also suggest the user check for typos in the Latex code.

For example, if the user wants to convert this code with a typo:
```
\begin{bmatrix}
x \\
y \\
z
\end{bmatrx}
```
The GUI will not show the image without an explanation.

![image](https://user-images.githubusercontent.com/37006239/106506025-ba613b00-648e-11eb-8724-79205c482fa3.png)

However, the terminal shows the tool failed to show the image.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\anton\anaconda3\envs\latex2github\lib\tkinter\__init__.py", line 1884, in __call__
    return self.func(*args)
  File "E:\repos\latex-to-github-app\latex-to-github-app.py", line 177, in encodeLaTeX
    self.show_image()
  File "E:\repos\latex-to-github-app\latex-to-github-app.py", line 186, in show_image
    self.page = urllib.request.urlopen(self.github_url).read()
  File "C:\Users\anton\anaconda3\envs\latex2github\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\anton\anaconda3\envs\latex2github\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\anton\anaconda3\envs\latex2github\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\anton\anaconda3\envs\latex2github\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\anton\anaconda3\envs\latex2github\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\anton\anaconda3\envs\latex2github\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by artmenlope** [comment]
Hello, Antonio. Thank you so much for your feedback. 

I have implemented your suggestion. Now, when a urllib.error.HTTPError is raised, an error message will be displayed telling that there was an error and suggesting to check the LaTeX code for typos. I have kept the full exception showing in the terminal for additional information.  

In this update I have also implemented right-click mouse copy-cut-paste menus for the text widgets.

If you have any other suggestion, please do not hesitate to let me know.
